# -*- coding: utf-8 -*-
"""a_gentle_introduction_to_tsl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eSzn-KIbEqBJJQXyAAmj_i-8O5kqhPrq

# A Gentle Introduction to `tsl`

### Graph time-series forecasting with Torch Spatiotemporal

---

In this tutorial, we will use [**Torch Spatiotemporal (`tsl`)**](https://torch-spatiotemporal.readthedocs.io/) to build and train a custom **Spatiotemporal Graph Neural Network (STGNN)** for traffic forecasting.

A graph time series contains observations collected:

- over a sequence of **time steps**;
- at multiple **sensor nodes**;
- with relationships between sensors represented by a **graph**.

`tsl` supports the complete graph time-series forecasting workflow:

1. load and inspect the data;
2. construct graph connectivity;
3. create input-window and target pairs;
4. split and scale the data;
5. create PyTorch mini-batches;
6. define temporal and graph-based model components;
7. train, validate and test the model;
8. interpret metrics and forecasts.

This notebook is adapted from the official *A Gentle Introduction to tsl* tutorial and retains its main workflow and Time-then-Space model.

> <font color="#1a73e8" size="4">**💡 Question:**</font>
>
> <font size="3">In a traffic forecasting problem, what could the nodes, node features, and graph edges represent?</font>

## Quickstart

Google Colab already includes PyTorch. We will install the PyTorch Geometric extensions, Torch Spatiotemporal and TensorBoard required by this tutorial.

The compiled PyTorch Geometric extensions are selected to match the PyTorch and CUDA build available in the Colab runtime. Fixed package releases are used to reduce version-related differences during the practical session.
"""

# Install the packages required by TSL and PyTorch Geometric.
import os
import torch

os.environ["TORCH"] = torch.__version__
print(f"PyTorch version: {torch.__version__}")

# !pip install -q torch-scatter \
#     -f https://data.pyg.org/whl/torch-${TORCH}.html

# !pip install -q torch-sparse \
#     -f https://data.pyg.org/whl/torch-${TORCH}.html

# !pip install -q torch-geometric==2.8.0.post1
# !pip install -q torch-spatiotemporal==0.9.5

"""For installation outside Google Colab, refer to the official
[TSL installation guide](https://torch-spatiotemporal.readthedocs.io/en/latest/usage/quickstart.html)
and
[PyTorch Geometric installation guide](https://pytorch-geometric.readthedocs.io/en/latest/install/installation.html).

Next, we will verify the installed versions and confirm that the libraries can be imported successfully.

henok.moges@uct.ac.za
"""

import sys

import numpy as np
import pandas as pd
import torch
import torch_geometric
import tsl

print(f"Python version : {sys.version.split()[0]}")
print(f"tsl version    : {tsl.__version__}")
print(f"PyTorch version: {torch.__version__}")
print(f"PyG version    : {torch_geometric.__version__}")
print(f"CUDA available : {torch.cuda.is_available()}")

pd.options.display.float_format = "{:.2f}".format
np.set_printoptions(edgeitems=3, precision=3)
torch.set_printoptions(edgeitems=2, precision=3)

"""### Usage

`tsl` provides more than neural-network layers. In this tutorial, we will focus on two main parts of its workflow:

- **Data loading and preprocessing**  
  Tools for downloading, storing, transforming and preparing spatiotemporal data for neural models.

- **Modelling and inference**  
  Models and training utilities that use spatiotemporal data for tasks such as forecasting and imputation.

We will first prepare the data and then use it to train a forecasting model.

## Loading and Preprocessing Data

### Loading a tabular dataset

`tsl` includes several datasets commonly used in spatiotemporal forecasting research. They are available through the [`tsl.datasets`](https://torch-spatiotemporal.readthedocs.io/en/latest/modules/datasets.html) module.

In this tutorial, we will use **METR-LA**, a widely used traffic forecasting benchmark. It contains traffic-speed measurements collected from **207 loop detectors** on highways in Los Angeles County.

The measurements were recorded every **5 minutes** over approximately four months, from March through June 2012.

We can download and load the dataset using the `MetrLA` class.
"""

from tsl.datasets import MetrLA

# Download the dataset on the first run and cache it locally.
dataset = MetrLA(root="./data")

print(dataset)

"""All datasets in `tsl` inherit from the base
[`tsl.datasets.Dataset`](https://torch-spatiotemporal.readthedocs.io/en/latest/modules/datasets_prototypes.html#tsl.datasets.prototypes.Dataset)
class, which provides a common interface for spatiotemporal data.

The METR-LA observations have shape:

```text
(time, nodes, features)
```

For this dataset:

- **34,272 time steps** — one observation every 5 minutes;
- **207 nodes** — traffic loop detectors;
- **1 feature** — traffic speed at each detector.

Therefore:

```text
(34,272, 207, 1)
```

The dataset object also provides metadata and graph-related information used during preprocessing.
"""

missing_percentage = (1 - dataset.mask.mean()) * 100

print(f"Sampling period: {dataset.freq}")
print(f"Has missing values: {dataset.has_mask}")
print(f"Percentage of missing values: {missing_percentage:.2f}%")
print(f"Mask shape: {dataset.mask.shape}")
print(f"Has covariates: {dataset.has_covariates}")
print(f"Covariates: {', '.join(dataset.covariates.keys())}")

"""The dataset contains missing observations. The binary `dataset.mask` has the same
time, node and feature dimensions as the observations:

- `1` indicates a valid observation;
- `0` indicates a missing observation.

METR-LA also provides `dist`, a static matrix containing pairwise distances
between sensor nodes. TSL exposes this information as a dataset covariate:

```python
dataset.dist
```

The distance matrix is graph-related information, but it is not yet the graph connectivity used by the model.

"""

print(f"Distance matrix shape: {dataset.dist.shape}")

pd.DataFrame(dataset.dist).iloc[:8, :8]

"""The distance matrix has one row and one column for each sensor. Each finite
entry represents the available distance from one sensor to another, while
`inf` denotes sensor pairs for which no finite connection distance is provided.

This matrix is graph-related information, but it is not yet the adjacency
matrix used by the model. Later, we will transform these distances into sensor
similarities and graph connections.

Next, let us inspect the traffic-speed observations in tabular form.
"""

speed_df = dataset.dataframe()

print(f"DataFrame shape: {speed_df.shape}")
speed_df.head()

"""#### Inspecting one sensor time series

Before constructing the graph, we inspect three days of traffic speed at the first sensor. This shows the temporal variation that the forecasting model must represent.

"""

import matplotlib.pyplot as plt

# First three days: 3 × 24 × 12 five-minute observations.
sensor_idx = 0
sensor_series = speed_df.iloc[:864, sensor_idx]
sensor_column = speed_df.columns[sensor_idx]
sensor_id = sensor_column[0] if isinstance(sensor_column, tuple) else sensor_column

plt.figure(figsize=(14, 4))
plt.plot(sensor_series.index, sensor_series.values)
plt.title(f"Traffic speed at sensor {sensor_id} - first three days")
plt.xlabel("Time")
plt.ylabel("Speed (mph)")
plt.grid(alpha=0.3)
plt.tight_layout()

"""#### Connecting sensors

The traffic observations tell us what was measured at each sensor over time, but
they do not specify how the sensors are related.

To use a graph-based model, we must define connections between the sensor nodes.

`dataset.get_similarity()` computes pairwise node similarities using information
provided with the dataset. The available methods are stored in
`dataset.similarity_options`, and the default method is given by
`dataset.similarity_score`.
"""

print(f"Default similarity: {dataset.similarity_score}")
print(f"Available similarity options: {dataset.similarity_options}")

sim = dataset.get_similarity("distance")

print(f"\nSimilarity matrix shape: {sim.shape}")
pd.DataFrame(sim).iloc[:8, :8]

"""The distance based similarity between sensors \(i\) and \(j\) is computed as

$$
w^{i,j} =
\begin{cases}
\exp\left(-\dfrac{\operatorname{dist}(i,j)^2}{\gamma}\right),
& \operatorname{dist}(i,j) \leq \delta, \\[6pt]
0, & \text{otherwise},
\end{cases}
$$

where:

- $\operatorname{dist}(i,j)$ is the distance from sensor $i$ to sensor $j$;
- $\gamma$ controls how quickly similarity decreases with distance;
- $\delta$ is a distance cut-off.

Nearby sensors receive larger similarity values, while sufficiently distant or
unconnected sensor pairs receive zero similarity.

The similarity matrix is not necessarily symmetric because the preprocessed
distance matrix is not symmetric.

We will now use `dataset.get_connectivity()` to:

1. obtain the default distance-based similarities;
2. remove similarity values below `0.1`;
3. remove self-connections;
4. normalise the edge weights;
5. return the graph in PyTorch Geometric's sparse `edge_index` layout.

> <font color="#1a73e8" size="4">**💡 Question:**</font>
>
> <font size="3">What is the difference between the distance matrix, similarity matrix and graph connectivity?</font>
"""

connectivity = dataset.get_connectivity(
    threshold=0.1,
    include_self=False,
    normalize_axis=1,
    layout="edge_index",
)

"""The graph construction performs the following operations:

- compute the distance-based similarity matrix;
- set similarities below `0.1` to zero (`threshold=0.1`);
- remove self-loops (`include_self=False`);
- normalise incoming edge weights (`normalize_axis=1`);
- return PyTorch Geometric's sparse COO representation (`layout="edge_index"`).

The returned connectivity is:

```python
(edge_index, edge_weight)
```
"""

edge_index, edge_weight = connectivity

print(f"edge_index shape: {edge_index.shape}")
print(edge_index)

print(f"\nedge_weight shape: {edge_weight.shape}")
print(edge_weight)

"""In the sparse COO representation:

- `edge_index` has shape `[2, E]`, where \(E\) is the number of edges;
- its first row contains source-node indices;
- its second row contains target-node indices;
- `edge_weight` contains one weight for each edge.

This representation stores only the existing graph connections rather than all
\(N^2\) possible node pairs.

The same graph can also be represented as a dense weighted adjacency matrix

$$
A \in \mathbb{R}^{N \times N}.
$$
"""

from tsl.ops.connectivity import edge_index_to_adj

adj = edge_index_to_adj(edge_index, edge_weight)

print(f"Adjacency matrix shape: {adj.shape}")
pd.DataFrame(adj).iloc[:8, :8]

"""#### Visualising the graph connectivity

The sparse edge representation can also be visualised as a dense weighted
adjacency matrix.

Rows represent target nodes, columns represent source nodes, and the colour
intensity represents the normalised edge weight.
"""

plt.figure(figsize=(7, 6))

image = plt.imshow(
    adj,
    aspect="auto",
    interpolation="nearest",
    origin="lower",
    extent=[0, adj.shape[1], 0, adj.shape[0]],
)

plt.colorbar(image, label="Normalised edge weight")
plt.xlabel("Source node")
plt.ylabel("Target node")
plt.title("METR-LA weighted adjacency matrix")
plt.tight_layout()

"""The sparse edge weights can be retrieved from the dense adjacency matrix.

TSL follows the PyTorch Geometric convention in which an edge from source
\(i\) to target \(j\) is stored at adjacency entry \(A_{j,i}\). This explains
the reversed indexing order below.
"""

source = edge_index[0]
target = edge_index[1]

print("Sparse edge weights:\n", adj[target, source])

"""### Building a PyTorch-ready dataset

[`SpatioTemporalDataset`](https://torch-spatiotemporal.readthedocs.io/en/latest/modules/data_pytorch_datasets.html#tsl.data.SpatioTemporalDataset)
converts the complete time series into PyTorch-ready forecasting samples.

It handles:

- sliding-window input–target pairs;
- graph connectivity and missing-value masks;
- conversion and organisation of data as model-ready tensors.
"""

from tsl.data import SpatioTemporalDataset

torch_dataset = SpatioTemporalDataset(
    target=dataset.dataframe(),
    connectivity=connectivity,
    mask=dataset.mask,
    window=12,
    horizon=12,
    stride=1,
)

print(torch_dataset)

"""The original time series is divided into overlapping forecasting samples:

- `window=12`: use the previous 12 time steps as input;
- `horizon=12`: predict the following 12 time steps;
- `stride=1`: move forward by one time step to create the next sample.

Because METR-LA is sampled every 5 minutes, each sample uses one hour of past
traffic data to forecast the next hour. The complete input–target sample spans
24 time steps.

<p align="center">
  <img src="https://torch-spatiotemporal.readthedocs.io/en/latest/_images/sliding_window.svg" width="500em">
</p>

> <font color="#1a73e8" size="4">**💡 Question:**</font>
>
> <font size="3">What real-world periods do `window=12`, `horizon=12`, and `stride=1`
> represent for this dataset?</font>

### Spatiotemporal graph signals in TSL

Each item in `torch_dataset` is a spatiotemporal forecasting sample containing:

- a past input window;
- a future forecasting target;
- the sensor graph;
- a validity mask for the target values.

Samples can be accessed using ordinary Python indexing.
"""

sample = torch_dataset[0]

print(sample)

"""A sample is represented by [`tsl.data.Data`](https://torch-spatiotemporal.readthedocs.io/en/latest/modules/data_objects.html#tsl.data.Data),
which extends the PyTorch Geometric `Data` object for spatiotemporal signals.

The main attributes used in this tutorial are:

- `sample.input.x`: the past input window;
- `sample.target.y`: the future forecasting target;
- `sample.edge_index`: graph connections in sparse COO format;
- `sample.edge_weight`: the corresponding graph weights;
- `sample.mask`: valid values in the forecasting target;
- `sample.pattern`: labels describing tensor dimensions such as time, nodes,
  features and edges.

We will inspect these tensors and their shapes next.

#### Input and target views

`Data.input` and `Data.target` provide views of the tensors stored in the same `Data` object. In this tutorial, `sample.input` contains the historical window and graph inputs, while `sample.target` contains the future traffic-speed target.
"""

sample.input.to_dict()

sample.target.to_dict()

"""#### Mask and transformations

`sample.mask` identifies valid forecasting targets.

`sample.transform` stores any preprocessing transformations associated with the
sample. No transformation has been added yet.

"""

if sample.has_mask:
    print(sample.mask)
else:
    print("Sample has no mask.")

if sample.has_transform:
    print(sample.transform)
else:
    print("Sample has no transformations.")

"""#### Tensor patterns

The `pattern` mapping describes the meaning of each tensor dimension:

- `t`: time steps;
- `n`: nodes;
- `e`: edges;
- `f`: features;
- `b`: batch.
"""

print("Tensor patterns:")
print(sample.pattern)

print("\nSample shapes:")
print(sample)

"""### Batching spatiotemporal graph signals

Multiple forecasting samples can be stacked into a batch while sharing the same
sensor graph.

"""

batch = torch_dataset[:5]

print(batch)

"""The batch dimension `b` is added to the time-varying tensors:

- `x`: historical input windows;
- `y`: future targets;
- `mask`: valid target values.

For five samples:

```text
[batch, time, nodes, features]
[5, 12, 207, 1]
```

The graph does not receive an additional batch dimension because all samples share the same fixed sensor graph.

> **Interpret the output**
>
> What do the dimensions `[5, 12, 207, 1]` represent?

### Preparing the dataset for training

Before training, we need to:

1. split the forecasting samples chronologically into training, validation and
   test sets;
2. scale the data using statistics computed from the training set.

[`SpatioTemporalDataModule`](https://torch-spatiotemporal.readthedocs.io/en/latest/modules/data_datamodule.html#tsl.data.datamodule.SpatioTemporalDataModule)
coordinates the data splits, preprocessing and mini-batch creation used during
training.
"""

from tsl.data.datamodule import SpatioTemporalDataModule, TemporalSplitter
from tsl.data.preprocessing import StandardScaler

# Standardise the traffic feature across training times and sensor nodes.
scalers = {
    "target": StandardScaler(axis=(0, 1))
}

# Split samples chronologically:
# |---------- complete dataset ----------|
# |------ train ------|-- val --|-- test --|
splitter = TemporalSplitter(
    val_len=0.1,
    test_len=0.2,
)

dm = SpatioTemporalDataModule(
    dataset=torch_dataset,
    scalers=scalers,
    splitter=splitter,
    batch_size=64,
)

print(dm.shape)

"""The data module uses a **lazy setup**: creating `dm` stores the configuration,
but does not yet split or scale the data.

We perform these operations explicitly by calling `dm.setup()`.
"""

dm.setup()

print(dm)

"""During `setup()`, the data module:

1. divides the forecasting samples into chronological training, validation and
   test sets;
2. fits the scaler using only the training data;
3. applies the fitted transformation consistently to the three subsets.

> <font color="#1a73e8" size="4">**💡 Question:**</font>
>
> <font size="3">Why must the scaler be fitted only on the training data?</font>

#### Splitters

A splitter defines how samples are assigned to the training, validation and test
sets.

Here, `TemporalSplitter` preserves chronological order rather than randomly
dividing the time series.

[Read more about TSL splitters](https://torch-spatiotemporal.readthedocs.io/en/latest/modules/data_datamodule.html#splitters).

#### Scalers

TSL scalers provide methods similar to those in scikit-learn:

- `fit`;
- `transform`;
- `fit_transform`;
- `inverse_transform`.

`StandardScaler` subtracts the training mean and divides by the training
standard deviation. Predictions can later be transformed back to the original
traffic-speed units.

[Read more about TSL scalers](https://torch-spatiotemporal.readthedocs.io/en/latest/modules/data_preprocessing.html#scalers).

## Building a Spatiotemporal Graph Neural Network

We will now build a simple forecasting model that combines:

1. **temporal processing** — learning from the recent history at each sensor;
2. **spatial processing** — exchanging information between connected sensors;
3. **multi-step decoding** — predicting the next 12 traffic observations.

The neural-network components used in TSL are available through the
[`tsl.nn`](https://torch-spatiotemporal.readthedocs.io/en/latest/modules/nn.html)
module.

### The `tsl.nn` module

The main neural-network submodules are organised by increasing level of
abstraction:

```text
tsl.nn
├── layers
├── blocks
└── models
````

* **Layers** implement individual neural-network operations.
* **Blocks** combine layers into reusable components.
* **Models** assemble layers and blocks into complete architectures.

In this tutorial, we will combine existing TSL layers and blocks inside a custom
PyTorch model.

#### Layers

A layer performs a specific transformation of its input.

The spatial layer used in this tutorial is
[`DiffConv`](https://torch-spatiotemporal.readthedocs.io/en/latest/modules/nn_layers.html#tsl.nn.layers.graph_convs.DiffConv),
which propagates node representations through the sensor graph using
`edge_index` and `edge_weight`.

#### Blocks

A block combines one or more operations into a reusable component.

We will use the
[`RNN`](https://torch-spatiotemporal.readthedocs.io/en/latest/modules/nn_blocks.html#tsl.nn.blocks.encoders.RNN)
encoder block with a GRU cell to process the temporal dimension.

The same GRU parameters are shared across all sensor nodes.

#### Models

A model combines layers and blocks into a complete mapping from inputs to
forecasts.

Our model will receive:

- a traffic input window `x`;
- graph connections `edge_index`;
- graph weights `edge_weight`;

and return a forecast for all nodes over the required prediction horizon.

### Designing a custom Time-then-Space STGNN

We will follow a **Time-then-Space** architecture.

#### 1. Encode the input

A linear layer maps the traffic feature at each sensor into a hidden
representation. A learnable node embedding is then added to represent
sensor-specific characteristics.

#### 2. Process time

A shared GRU processes the 12-step history independently at each sensor and
returns one temporal representation per node:

```text
[batch, time, nodes, features]
                ↓ GRU
[batch, nodes, hidden features]
````

At this stage, each sensor has summarised its own recent history, but it has not
yet received information from connected nodes, unless physical neighbourhood is specifically intended.

#### 3. Process space

`DiffConv` propagates the temporal representations through the sensor graph:

```text
temporal node representations
          + sensor graph
                ↓
spatially informed node representations
```


#### 4. Produce the forecast

A linear decoder maps each final node representation to all 12 future time
steps and reshapes the output as:

```text
[batch, horizon, nodes, features]
```

### Code map: Time-then-Space model

| Step | Role | PyTorch/TSL component |
| :--- | :--- | :--- |
| **Encode** | Map raw traffic values to a hidden representation | `nn.Linear`, `NodeEmbedding` |
| **Time** | Process the 12-step history at each node | `RNN` with a GRU cell |
| **Space** | Propagate representations over the graph | `DiffConv` |
| **Decode** | Predict all 12 future steps | `nn.Linear`, `Rearrange` |
"""

import torch.nn as nn

from einops.layers.torch import Rearrange
from tsl.nn.blocks.encoders import RNN
from tsl.nn.layers import NodeEmbedding, DiffConv


class TimeThenSpaceModel(nn.Module):
    def __init__(
        self,
        input_size: int,
        n_nodes: int,
        horizon: int,
        hidden_size: int = 32,
        rnn_layers: int = 1,
        gnn_kernel: int = 2,
    ):
        super().__init__()

        self.encoder = nn.Linear(input_size, hidden_size)

        self.node_embeddings = NodeEmbedding(n_nodes, hidden_size)

        self.time_nn = RNN(
            input_size=hidden_size,
            hidden_size=hidden_size,
            n_layers=rnn_layers,
            cell="gru",
            return_only_last_state=True,
        )

        self.space_nn = DiffConv(
            in_channels=hidden_size,
            out_channels=hidden_size,
            k=gnn_kernel,
        )

        self.decoder = nn.Linear(hidden_size, input_size * horizon)

        self.rearrange = Rearrange(
            "b n (t f) -> b t n f",
            t=horizon,
        )

    def forward(self, x, edge_index, edge_weight):
        # x: [batch, time, nodes, input features]
        x_enc = self.encoder(x)

        # Add a learnable node-specific representation.
        x_emb = x_enc + self.node_embeddings()

        # Summarise the historical sequence at each node.
        # [batch, time, nodes, hidden] -> [batch, nodes, hidden]
        h = self.time_nn(x_emb)

        # Propagate the temporal node representations over the graph.
        z = self.space_nn(h, edge_index, edge_weight)

        # Produce all values in the prediction horizon.
        # [batch, nodes, hidden] -> [batch, nodes, horizon × features]
        x_out = self.decoder(z)

        # [batch, nodes, horizon × features]
        # -> [batch, horizon, nodes, features]
        x_horizon = self.rearrange(x_out)

        return x_horizon

"""> <font color="#1a73e8" size="4">**💡 Question:**</font>
>
> <font size="3">what information would be unavailable to the model if the GRU representation were passed directly to
> the decoder without applying `DiffConv`?
</font>

We now set the model hyperparameters and instantiate the
Time-then-Space STGNN.
"""

from tsl.nn.models import GraphWaveNetModel, AGCRNModel

hidden_size = 32   #@param
rnn_layers = 1     #@param
gnn_kernel = 2     #@param

input_size = torch_dataset.n_channels
n_nodes = torch_dataset.n_nodes
horizon = torch_dataset.horizon

simpleSTGNN = TimeThenSpaceModel(input_size=input_size,
                           n_nodes=n_nodes,
                           horizon=horizon,
                           hidden_size=hidden_size,
                           rnn_layers=rnn_layers,
                           gnn_kernel=gnn_kernel)

GWN = GraphWaveNetModel(input_size=input_size,
                        output_size=1,
                        horizon=horizon,
                       n_nodes=n_nodes)

AGCR = AGCRNModel(input_size=input_size,
                output_size=1,
                horizon=horizon,
                 n_nodes=n_nodes)

print("simpleTTS: "+str(simpleSTGNN))
# print_model_size(simpleSTGNN)
print("GWN: "+str(GWN))
# print_model_size(GWN)
print("AGCR: "+str(AGCR))
# print_model_size(AGCR)

"""The data pipeline and forecasting model are now defined.

Next, we configure the training objective, evaluation metrics, optimiser,
logging and model checkpointing.

### Setting up training

We will use PyTorch Lightning to coordinate model optimisation, validation,
metric logging and checkpointing.

TSL integrates with PyTorch Lightning through its `Predictor` engine. The live
tutorial will use a reduced training budget, while retaining the same model,
loss function and evaluation metrics.

#### The `Predictor`

[`tsl.engines.Predictor`](https://torch-spatiotemporal.readthedocs.io/en/latest/modules/engines.html#tsl.engines.Predictor)
wraps the forecasting model and specifies:

- the loss function;
- the optimiser;
- the evaluation metrics used during training, validation and testing.

It is implemented as a PyTorch Lightning `LightningModule`, allowing it to be
used directly with the Lightning `Trainer`.
"""

from tsl.metrics.torch import MaskedMAE, MaskedMAPE
from tsl.engines import Predictor

loss_fn = MaskedMAE()

metrics = {'mae': MaskedMAE(),
           'mape': MaskedMAPE(),
           'mae_at_15': MaskedMAE(at=2),  # '2' indicates the third time step,
                                          # which correspond to 15 minutes ahead
           'mae_at_30': MaskedMAE(at=5),
           'mae_at_60': MaskedMAE(at=11)}

# setup predictor
predictor = Predictor(
    model=GWN,                   # our initialized model
    optim_class=torch.optim.Adam,  # specify optimizer to be used...
    optim_kwargs={'lr': 0.001},    # ...and parameters for its initialization
    loss_fn=loss_fn,               # which loss function to be used
    metrics=metrics                # metrics to be logged during train/val/test
)

"""TensorBoard records training and validation metrics so that convergence and the train-validation gap can be inspected during and after training."""

from pytorch_lightning.loggers import TensorBoardLogger

logger = TensorBoardLogger(
    save_dir="logs",
    name="tsl_intro",
)

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir logs

"""The PyTorch Lightning `Trainer` manages the optimisation and validation loops. Passing the TSL data module to `trainer.fit()` provides the training and validation data loaders together with the preprocessing configuration.

For the live tutorial, we use:

- 10 epochs;
- 50 training batches per epoch;
- the complete validation set after each epoch.

This gives at most 500 optimisation updates. It demonstrates the full workflow without claiming a fully converged benchmark result.
"""

import pytorch_lightning as pl
from pytorch_lightning.callbacks import ModelCheckpoint

checkpoint_callback = ModelCheckpoint(
    dirpath=logger.log_dir,
    save_top_k=1,
    monitor="val_mae",
    mode="min",
)

trainer = pl.Trainer(
    max_epochs=10,
    accelerator="auto",
    devices=1,
    logger=logger,
    limit_train_batches=50,
    callbacks=[checkpoint_callback],
)

trainer.fit(
    predictor,
    datamodule=dm,
)

"""### Testing

We now evaluate the checkpoint with the lowest validation MAE on the
chronologically held-out test set.

The test set has not been used to update model parameters or select the
checkpoint. It is used only for the final evaluation.
"""

best_checkpoint = checkpoint_callback.best_model_path

print(f"Best checkpoint: {best_checkpoint}")

test_results = trainer.test(
    model=predictor,
    datamodule=dm,
    ckpt_path=best_checkpoint,
    weights_only=False,
)

"""#### Inspecting one forecast

Aggregate metrics summarise performance across many samples and sensors, but
they do not show the temporal pattern of an individual forecast.

We will compare the predicted and observed traffic speeds for one sensor in one
test sample.
"""

# Obtain one mini-batch from the chronological test set.
test_batch = next(iter(dm.test_dataloader()))
test_batch = test_batch.to(predictor.device)

predictor.eval()

with torch.no_grad():
    y, y_hat, mask = predictor.predict_batch(
        test_batch,
        postprocess=True,
        return_target=True,
    )

sample_idx = 0
node_idx = 0
feature_idx = 0

actual = (
    y[sample_idx, :, node_idx, feature_idx]
    .detach()
    .cpu()
    .numpy()
)

predicted = (
    y_hat[sample_idx, :, node_idx, feature_idx]
    .detach()
    .cpu()
    .numpy()
)

# Hide missing observations from the actual-value curve.
if mask is not None:
    valid = (
        mask[sample_idx, :, node_idx, feature_idx]
        .detach()
        .cpu()
        .numpy()
        .astype(bool)
    )
    actual = np.where(valid, actual, np.nan)

forecast_minutes = np.arange(1, horizon + 1) * 5
sensor_name = speed_df.columns[node_idx]

plt.figure(figsize=(8, 4))
plt.plot(
    forecast_minutes,
    actual,
    marker="o",
    label="Actual",
)
plt.plot(
    forecast_minutes,
    predicted,
    marker="o",
    label="Predicted",
)

plt.xlabel("Forecast horizon (minutes)")
plt.ylabel("Traffic speed")
plt.title(f"Actual and predicted traffic speed — sensor {sensor_name}")
plt.xticks(forecast_minutes)
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

"""### Summary

This tutorial extends the earlier single node, one-step MLP workflow to a graph time-series forecasting pipeline:

| Earlier DNN assignment | This tutorial |
| :--- | :--- |
| Selected sensor nodes | Full 207-node METR-LA network |
| One-step prediction | 12-step direct forecast |
| Feedforward MLP | GRU followed by diffusion convolution |
| Exploratory 80:20 train-val split | Chronological train-val-test split |
| Model selection on validation data | Validation-based checkpointing followed by final testing |

A single forecast plot is illustrative so conclusions require aggregate evaluation and for a full experiment repeated runs and appropriate baseline comparisons.
"""

